settings:

 #Desative comandos específicos
 #em todo o seu servidor.
  fly-CMD: true
  help-CMD: true
  invsee-CMD: true
  vanish-CMD: true
  colorchat-CMD: true

#Messages: Estas são as mensagens executadas
#pelos comandos do NowEssentials.
messages:
  sem-permissao: "&cVocê não pode executar este comando!"
  prefixo: "&b[NowEssentials]"

  flight-usage: "%prefixo% &fPor favor, use &a/voar"
  ativo-flight: "%prefixo% &fSeu &aVoo &ffoi ativado!"
  desativo-flight: "%prefixo% &fSeu &cVoo &ffoi desativado!"
  flight-permission: "NowEssentials.Fly"

  help-usage: "%prefixo% &fPor favor, use &a/ajuda"
  help-permission: "NowEssentials.Help"

  invsee-usage: "%prefixo% &fPor favor, use &a/invVer <jogador>"
  invsee-glitch: "%prefixo% &cVocê não pode abrir seu inventário!"
  invsee-permission: "NowEssentials.Vanish"

  vanish-usage: "%prefixo% &fPor favor, use &a/invisivel"
  ativo-vanish: "%prefixo% &fSua &eInvisibilidade &ffoi ativada!"
  desativo-vanish: "%prefixo% &fSua &cInvisibilidade &ffoi desativada!"
  vanish-permission: "NowEssentials.Vanish"