name: NowEssentials
version: 2.0
author: TioStitch
description: Um sistema de comandos/funções essenciais.
main: com.tiostitch.essentials.NowEssentials
commands:
  fly:
    aliases: [voar]
    description: Comando de voar.
  help:
    description: Comando de ajuda.
  vanish:
    aliases: [v, invi]
    description: Comando de invisibilidade.
  invsee:
    aliases: [invver, verinv]
    description: Comando de ver inventário.
  baudofim:
    aliases: [ec, enderchest]
    description: Comando de ver baú do fim.